language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"


before_script:
  - composer install
  - "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.45.0.jar"
  - "java -jar selenium-server-standalone-2.45.0.jar > /dev/null &"
  - sleep 5

script:
  - php ./bin/behat